spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL:http://localhost:8090/realms/The-Homeric-Odyssey-Vendor}
          jwk-set-uri: ${KEYCLOAK_BASE_JWK:http://localhost:8090/realms/The-Homeric-Odyssey-Vendor/protocol/openid-connect/certs}
  application:
    name: event-log
  datasource:
    password: ${DATASOURCE_PASSWORD:example}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/event-log}
    username: ${DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/changelog-master.yaml

event-log:
  api:
    url: ${EVENT_LOG_URL:http://localhost:8092}

resource-server:
  client-id: ${KEYCLOAK_CLIENT_ID:auth-server-client}